version: "3.4"
services:
  actix_react:
    container_name: "actix_react"
    build:
      context: .
      dockerfile: "Dockerfile.test"
      cache_from: 
        - rust:latest
    links:
      - "postgres"
    depends_on:
      - "postgres"
    environment:
      - DATABASE_URL=postgres://docker:docker@postgres:5432/docker
    networks:
      - actix_api
    volumes: 
      - ./:/app
    tty: true
    ports:
      - "4000:4000"
    
  postgres:
    image: postgres:alpine
    volumes:
      - pg_actix:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "docker" 
      POSTGRES_PASSWORD: "docker"
      PGPASSWORD: "docker"
    networks:
      - actix_api
    ports:
      - "5432:5432"

networks:
  actix_api:
    driver: bridge

volumes:
    pg_actix:
        driver: local